# ============================
# WEBSite — Modules activables
# ============================

# Scripts principaux
MODULE_SERVE=true
MODULE_BUILD=true
MODULE_DEPLOY=true

# Scripts utilitaires
MODULE_CLEAN=true
MODULE_WATCH=true
MODULE_LINT=true
MODULE_INIT=true

# Scripts avancés
MODULE_OPTIMIZE_IMAGES=false
MODULE_BACKUP=true
MODULE_ROLLBACK=false
MODULE_HTTPS_SERVER=false
MODULE_TESTS=false

# CI/CD
MODULE_CI_BUILD=true
MODULE_CI_DEPLOY=true
MODULE_CI_CHECK=true
