# ============================
# WEBSite — Chemins principaux
# ============================

SRC_DIR="src"
DIST_DIR="dist"
DOCS_DIR="docs"
SCRIPTS_DIR="scripts"
CONFIG_DIR="config"

# Dossiers internes
CACHE_DIR=".cache"
TMP_DIR="tmp"

# Images
IMG_SRC="src/img"
IMG_DIST="dist/img"
