# ============================
# WEBSite — Configuration générale
# ============================

PROJECT_NAME="WEBSite"
VERSION="0.4"
ENVIRONMENT="development"   # development | production

# Serveur local
SERVER_PORT=8000
SERVER_HTTPS_PORT=8443

# Déploiement
DEPLOY_BRANCH="gh-pages"
DEPLOY_BUILD_FIRST=true
